In [1]:
# Libraries Used:

import io 
import zipfile
import pandas as pd
import requests
from scipy.io import arff

In [20]:
pip install missingno

Collecting missingno
  Downloading missingno-0.5.2-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from missingno) (2.2.4)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from missingno) (3.10.7)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from missingno) (1.16.3)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from seaborn->missingno) (2.3.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.2->seaborn->missingno) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.2->seaborn->missingno) (2025.2)
Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Installing collected packages: missingno
Successfully installed missingno-0.5.2
Note: you may need to restart the kernel to use updated packages.

# Downloading File from UCI

In [2]:
url = "https://archive.ics.uci.edu/static/public/365/polish+companies+bankruptcy+data.zip"
response = requests.get(url)
zip_file = zipfile.ZipFile(io.BytesIO(response.content))

In [3]:
data3, _ = arff.loadarff(io.TextIOWrapper(zip_file.open('3year.arff')))
df3 = pd.DataFrame(data3)

In [4]:
df3['class'] = df3['class'].astype(int)

In [5]:
df3

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.174190,0.41299,0.143710,1.34800,-28.9820,0.603830,0.219460,1.122500,1.19610,0.463590,...,0.163960,0.375740,0.83604,0.000007,9.7145,6.2813,84.291,4.3303,4.0341,0
1,0.146240,0.46038,0.282300,1.62940,2.5952,0.000000,0.171850,1.172100,1.60180,0.539620,...,0.027516,0.271000,0.90108,0.000000,5.9882,4.1103,102.190,3.5716,5.9500,0
2,0.000595,0.22612,0.488390,3.15990,84.8740,0.191140,0.004572,2.988100,1.00770,0.675660,...,0.007639,0.000881,0.99236,0.000000,6.7742,3.7922,64.846,5.6287,4.4581,0
3,0.024526,0.43236,0.275460,1.78330,-10.1050,0.569440,0.024526,1.305700,1.05090,0.564530,...,0.048398,0.043445,0.95160,0.142980,4.2286,5.0528,98.783,3.6950,3.4844,0
4,0.188290,0.41504,0.342310,1.92790,-58.2740,0.000000,0.233580,1.409400,1.33930,0.584960,...,0.176480,0.321880,0.82635,0.073039,2.5912,7.0756,100.540,3.6303,4.6375,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10498,0.002861,0.58067,-0.223860,0.51658,-31.8660,0.002861,0.002861,0.618550,1.01200,0.359170,...,0.011834,0.007966,0.98817,0.327360,38.1420,39.1500,42.202,8.6489,5.2646,1
10499,-0.051968,0.55254,0.147150,2.16980,12.7480,-0.051968,-0.034361,0.669830,0.94694,0.370110,...,-0.056037,-0.140410,1.05600,1.153000,14.4930,9.2851,32.761,11.1410,1.9276,1
10500,-0.135900,0.83954,-0.342010,0.46526,-145.3100,-0.219120,-0.131860,0.191130,1.09990,0.160460,...,0.144120,-0.846930,0.85427,0.814200,6.2737,9.6966,212.230,1.7198,1.5659,1
10501,0.009423,0.50028,0.261630,1.52300,-10.1580,0.009423,0.007700,0.989900,1.01230,0.495230,...,0.012186,0.019027,0.98781,0.000000,5.9675,4.3536,98.240,3.7154,7.8068,1
10502,-0.001775,0.94780,0.003729,1.00450,-50.2210,0.000000,0.002565,0.055122,2.12680,0.052245,...,0.023492,-0.033971,0.97208,2.398500,7.5512,3.9960,141.160,2.5857,12.2250,1

## Using just 3year.arff
 We decided to just use 3years rather than merging all 5 years in a dataframe. We had multiple reasons as to why it was simpler and safer than combining them.

- Since we are using only 3year our target variable will have a specific target. We will be predicting if a company will go bankrupt in 3 years rather than a span of 1-5 years if we merged the data.

- Using just 3year will mean that we will have zero data leakage. Having only one dataset means that every row represents a disctinctive company for that periods. We wont have to worry about the same company appearing in the training set and the test set.

- Now that we are only using one it is much easier to deal with the data, making it easier to interpret the results.

# Dataframe Info

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10503 entries, 0 to 10502
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Attr1   10503 non-null  float64
 1   Attr2   10503 non-null  float64
 2   Attr3   10503 non-null  float64
 3   Attr4   10485 non-null  float64
 4   Attr5   10478 non-null  float64
 5   Attr6   10503 non-null  float64
 6   Attr7   10503 non-null  float64
 7   Attr8   10489 non-null  float64
 8   Attr9   10500 non-null  float64
 9   Attr10  10503 non-null  float64
 10  Attr11  10503 non-null  float64
 11  Attr12  10485 non-null  float64
 12  Attr13  10460 non-null  float64
 13  Attr14  10503 non-null  float64
 14  Attr15  10495 non-null  float64
 15  Attr16  10489 non-null  float64
 16  Attr17  10489 non-null  float64
 17  Attr18  10503 non-null  float64
 18  Attr19  10460 non-null  float64
 19  Attr20  10460 non-null  float64
 20  Attr21  9696 non-null   float64
 21  Attr22  10503 non-null  float64
 22  Attr23  10460 non-null  float64
 23  Attr24  10276 non-null  float64
 24  Attr25  10503 non-null  float64
 25  Attr26  10489 non-null  float64
 26  Attr27  9788 non-null   float64
 27  Attr28  10275 non-null  float64
 28  Attr29  10503 non-null  float64
 29  Attr30  10460 non-null  float64
 30  Attr31  10460 non-null  float64
 31  Attr32  10402 non-null  float64
 32  Attr33  10485 non-null  float64
 33  Attr34  10489 non-null  float64
 34  Attr35  10503 non-null  float64
 35  Attr36  10503 non-null  float64
 36  Attr37  5767 non-null   float64
 37  Attr38  10503 non-null  float64
 38  Attr39  10460 non-null  float64
 39  Attr40  10485 non-null  float64
 40  Attr41  10301 non-null  float64
 41  Attr42  10460 non-null  float64
 42  Attr43  10460 non-null  float64
 43  Attr44  10460 non-null  float64
 44  Attr45  9912 non-null   float64
 45  Attr46  10485 non-null  float64
 46  Attr47  10417 non-null  float64
 47  Attr48  10503 non-null  float64
 48  Attr49  10460 non-null  float64
 49  Attr50  10489 non-null  float64
 50  Attr51  10503 non-null  float64
 51  Attr52  10417 non-null  float64
 52  Attr53  10275 non-null  float64
 53  Attr54  10275 non-null  float64
 54  Attr55  10503 non-null  float64
 55  Attr56  10460 non-null  float64
 56  Attr57  10503 non-null  float64
 57  Attr58  10474 non-null  float64
 58  Attr59  10503 non-null  float64
 59  Attr60  9911 non-null   float64
 60  Attr61  10486 non-null  float64
 61  Attr62  10460 non-null  float64
 62  Attr63  10485 non-null  float64
 63  Attr64  10275 non-null  float64
 64  class   10503 non-null  int64
dtypes: float64(64), int64(1)
memory usage: 5.2 MB

# Checking Data types

In [6]:
df3.dtypes

Attr1     float64
Attr2     float64
Attr3     float64
Attr4     float64
Attr5     float64
           ...
Attr61    float64
Attr62    float64
Attr63    float64
Attr64    float64
class       int64
Length: 65, dtype: object

# Detecting Missing Values

In [7]:
total_rows = len(df3)
missing_per_col = df3.isnull().sum()
missing_percent = (missing_per_col / total_rows) * 100

missing_summary = pd.DataFrame({
    'Missing Count': missing_per_col,
    'Missing Percent': missing_percent
})
missing_summary = missing_summary[missing_summary['Missing Count'] > 0].sort_values(by = 'Missing Count', ascending = False)

In [8]:
missing_summary

        Missing Count  Missing Percent
Attr37           4736        45.091879
Attr21            807         7.683519
Attr27            715         6.807579
Attr60            592         5.636485
Attr45            591         5.626964
Attr54            228         2.170808
Attr53            228         2.170808
Attr28            228         2.170808
Attr64            228         2.170808
Attr24            227         2.161287
Attr41            202         1.923260
Attr32            101         0.961630
Attr52             86         0.818814
Attr47             86         0.818814
Attr19             43         0.409407
Attr39             43         0.409407
Attr62             43         0.409407
Attr56             43         0.409407
Attr49             43         0.409407
Attr13             43         0.409407
Attr44             43         0.409407
Attr43             43         0.409407
Attr20             43         0.409407
Attr42             43         0.409407
Attr31             43         0.409407
Attr30             43         0.409407
Attr23             43         0.409407
Attr58             29         0.276112
Attr5              25         0.238027
Attr40             18         0.171380
Attr63             18         0.171380
Attr12             18         0.171380
Attr4              18         0.171380
Attr46             18         0.171380
Attr33             18         0.171380
Attr61             17         0.161859
Attr50             14         0.133295
Attr16             14         0.133295
Attr8              14         0.133295
Attr17             14         0.133295
Attr34             14         0.133295
Attr26             14         0.133295
Attr15              8         0.076169
Attr9               3         0.028563

# Checking For Outliers

In [9]:
X = df3.drop(columns = ['class'])

Q1 = X.quantile(0.25)
Q3 = X.quantile(0.75)
IQR = Q3 - Q1

outliers_matrix = (X < (Q1 - 1.5 * IQR)) | (X > (Q3 + 1.5 * IQR))

outliers_summary = pd.DataFrame({
    'Outlier Count': outliers_matrix.sum(),
    'Outlier Percent': (outliers_matrix.sum() / total_rows) * 100
}).sort_values(by = 'Outlier Count', ascending = False)

In [10]:
outliers_summary

        Outlier Count  Outlier Percent
Attr6            3170        30.181853
Attr27           2158        20.546511
Attr15           1799        17.128439
Attr55           1796        17.099876
Attr41           1777        16.918976
...               ...              ...
Attr38            325         3.094354
Attr10            305         2.903932
Attr2             290         2.761116
Attr3             271         2.580215
Attr29            170         1.618585

[64 rows x 2 columns]

In [11]:
X.describe().T[['min', '25%', '50%', '75%', 'max']]

                 min        25%        50%         75%          max
Attr1  -1.769200e+01   0.000686   0.043034    0.123805       52.652
Attr2   0.000000e+00   0.253955   0.464140    0.689330      480.730
Attr3  -4.797300e+02   0.017461   0.198560    0.419545       17.708
Attr4   2.080200e-03   1.040100   1.605600    2.959500    53433.000
Attr5  -1.190300e+07 -52.070750   1.579300   56.084000   685440.000
...              ...        ...        ...         ...          ...
Attr60  0.000000e+00   5.533150   9.952100   20.936000  3660200.000
Attr61 -6.590300e+00   4.486075   6.677300   10.587500     4470.400
Attr62 -2.336500e+06  40.737000  70.664000  118.220000  1073500.000
Attr63 -1.562200e-04   3.062800   5.139200    8.882600     1974.500
Attr64 -1.023000e-04   2.023350   4.059300    9.682750    21499.000

[64 rows x 5 columns]

In [12]:
X.skew()

Attr1      51.971750
Attr2      71.596019
Attr3     -71.691576
Attr4     101.305786
Attr5     -96.857582
             ...
Attr60     96.550112
Attr61     37.139765
Attr62    -61.737752
Attr63     36.053408
Attr64     31.967754
Length: 64, dtype: float64

# Check Class Imbalance

In [14]:
class_counts = df3['class'].value_counts()
class_percentages = df3['class'].value_counts(normalize = True) * 100

imbalance_summary = pd.DataFrame({'Count': class_counts, 'Percentage': class_percentages.round(2)})

In [15]:
imbalance_summary

       Count  Percentage
class
0      10008       95.29
1        495        4.71